"""
Script part of SCANN-ex github project
Related to "Practical Introduction to Side-Channel Extraction of Deep Neural Network Parameters" publication
"""

import sys, os, array, time
import numpy as np
import serial, math, secrets
from random import *
from ast import literal_eval
import struct
import pickle
import matplotlib.pyplot as plt


from sklearn import datasets
import tensorflow as tf
from tensorflow import keras

from variable_constructor import *



# -----------------------   Bin, float conversions and manip  ----------------------- #

def binary(num):
    return ''.join('{:0>8b}'.format(c) for c in struct.pack('!f', num))

def float_to_binary(my_number):
    return ''.join('{:0>8b}'.format(c) for c in struct.pack('!f', my_number))

def binaryToFloat(value):
    return struct.unpack('!f', struct.pack('!I', int(value, 2)))[0]

def bin_to_int(binary):
    return int(binary, 2)

def extract_bits(my_float, starting_position, nb_of_bit_to_extract):
    bin_value = float_to_binary(my_float)
    target_bin = bin_value[starting_position: starting_position + nb_of_bit_to_extract]
    corresponding_int = bin_to_int(target_bin)

    return (corresponding_int, target_bin)


# -----------------------   Calcul Hamming Weight ----------------------- #

_HW8_table = np.array([bin(x).count('1') for x in range(256)], dtype = np.uint8)

def hamming_weight_8(x):
    return _HW8_table[x]

def hamming_weight_16(x):
    return hamming_weight_8(x & 0xFF) + hamming_weight_8(x >> 8)

def hamming_weight_32(x):
    return hamming_weight_16(x & 0xFFFF) + hamming_weight_16(x >> 16)

def hamming_weight_64(x):
    return hamming_weight_8(x & 0xFFFFFFFF) + hamming_weight_32(x >> 32)

def EXP_hamming_weight_IEEE745(x):
    return hamming_weight_32(x)

def hamming_weight_IEEE745(x):
    return float_to_binary(x).count('1')



# -----------------------   Communication with STM32 board   ----------------------- #

def synchronisation_with_target(ser, debug=False):
    sync = False
    ret = None

    while (sync == False):
        ser.write(b"sync")
        ret = ser.read(3)
        if (ret == b"101"): # "101" has been chosen arbitrarily
            sync = True
            if (debug):
                print("Synchronised")
        else:
            if (debug):
                print ("Wrong ack reponse " + str(ret))



def send_NN_inputs_to_STM32(entry, output_size, ser):

    if not ser.isOpen():
        print ("Error: serial connection to be used isn't opened")
        sys.exit(-1)

    # Synchronisation loop
    synchronisation_with_target(ser, True)

    # Send inputs to the Neural Network
    input_sent = False
    input_size = len(entry)

    while(input_sent == False):
        for i in range(input_size):
            ser.write(binary(entry[i]).encode('ascii'))

        data_reception_ack = ser.read(21)
        if data_reception_ack == b"D:good data reception":
            input_sent = True
        else:
            print (data_reception_ack)

    # Wait for the end of the multiplication
    multiplication_effected = False

    while(multiplication_effected == False):
        mul_op_ack = ser.read(25)
        if mul_op_ack == b"D:Multiplication effected":
            multiplication_effected = True
        else:
            print (mul_op_ack)

    # wait for the output values generated by the STM32
    out_ack = b"000"
    while(out_ack != b"010"): # "010" has been chosen arbitrarily
        out_ack = ser.read(3)

    output_size = output_size
    output = np.zeros((output_size))
    for i in range(output_size):
        tmp = ser.read(4)
        output[i] = struct.unpack('f', tmp)[0]

    print ("Obtained output: " + str(output))

    return output


# -----------------------   Dataset Generation   ----------------------- #

def generate_random_dataset(dim0, dim1,
                            redondance=0,
                            normalize=False,
                            HW_to_impose=-1,
                            HW_coor=(-1,-1),
                            bin_to_impose="",
                            starting_position=-1):

    HW_craft_values  = False
    Bin_craft_values = False
    random_values    = False


    if (HW_to_impose==-1 and HW_coor==(-1,-1)) and (bin_to_impose=="" and starting_position==-1):
        random_values = True

    elif (HW_to_impose != -1 and HW_coor != (-1,-1)) and (bin_to_impose=="" and starting_position==-1):

        if HW_coor[0] > HW_coor[1]:
            print("Incorrect corredinates given")
            sys.exit(-1)

        distance = HW_coor[1] - HW_coor[0]
        if HW_to_impose > (distance):
            print("Impossible to apply given Hamming Weight")
            sys.exit(-1)

        HW_craft_values = True

    elif (HW_to_impose==-1 and HW_coor==(-1,-1)) and (bin_to_impose != "" and starting_position != -1):

        if 0 > starting_position or starting_position > 32:
            print("Incorrect starting position given")
            sys.exit(-1)

        if len(bin_to_impose) > 32:
            print("Bin word to apply is too long")
            sys.exit(-1)

        if starting_position + len(bin_to_impose) > 32:
            print("Impossible to apply given bin word according to given starting position")
            sys.exit(-1)

        Bin_craft_values = True

    else:
        print("Manipulation to apply isn't recognized")
        sys.exit(-1)


    dataset      = np.zeros((dim0, dim1), dtype=np.float32)
    HW_input     = np.zeros((dim0, dim1), dtype=np.uint16)

    if random_values:
        for i in range(dim0):
            for j in range(dim1):
                tmp = Variables_constructor(normalize=normalize)
                dataset[i, j]      = tmp()
                HW_input[i, j]     = tmp.HW
                del tmp

    elif HW_craft_values:
        for i in range(dim0):
            for j in range(dim1):
                tmp = Variables_constructor(normalize=normalize, HW_to_impose=HW_to_impose, coor_to_apply_HW=HW_coor)
                dataset[i, j]      = tmp()
                HW_input[i, j]     = tmp.HW
                del tmp

    elif Bin_craft_values:
        for i in range(dim0):
            for j in range(dim1):
                tmp = Variables_constructor(normalize=normalize, bin_to_impose=bin_to_impose, starting_point=starting_position)
                dataset[i, j]      = tmp()
                HW_input[i, j]     = tmp.HW
                del tmp

    else:
        print("Unnable to generate data")
        sys.exit(-1)

    if redondance == 0 or redondance == 1:
        return dataset, HW_input

    redondance_dataset      = np.zeros((dim0 * redondance, dim1), dtype=np.float32)
    redondance_HW_input     = np.zeros((dim0 * redondance, dim1), dtype=np.uint16)

    for i in range(dim0):
        for j in range(redondance):
            index = i*redondance + j
            redondance_dataset[index]      = dataset[i]
            redondance_HW_input[index]     = HW_input[i]

    return redondance_dataset, redondance_HW_input










if __name__ == '__main__':

    REDONDANCE = 1
    NB_ELEM_PER_INPUT  = 4
    NB_ELEM_PER_OUTPUT = 3

    tf.autograph.set_verbosity(0)
    nb_inference = 100

    with serial.Serial("COM10", 115200, timeout=1) as ser:
        chrono = Timer("Chrono")

        input_sent      = []
        output_received = []

        i = 0

        input_dataset, HW_input = generate_random_dataset(nb_inference,
                                                          NB_ELEM_PER_INPUT,
                                                          redondance=REDONDANCE,
                                                          normalize=False)
                                                          #bin_to_impose="0",
                                                          #starting_position=0)


        received_output = []

        while(i < nb_inference * REDONDANCE):
            entry = None
            print ("\n\n------ Inference "+str(i)+" requested: ------\n")

            entry = input_dataset[i]

            print ("\nPYTHON:")
            print ("Selected input: " + str(entry))
            print ("\nSTM32:")

            res = send_NN_inputs_to_STM32(entry, NB_ELEM_PER_OUTPUT, ser)
            received_output.append(res)

            i = i + 1
